version: "3.8"
services:
  nodeauth_db:
    container_name: nodeauth_db
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nodeauth
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    container_name: nodeauth_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
